### PR TITLE
Fixed CustomButtonResult when using radio buttons together with custom buttons

### PR DESCRIPTION
**Pull request by ygoe**
Hi,

I've fixed that radio/custom buttons bug I've reported on CodeProject. Is the GitHub code usually newer than the one on CodeProject?

Yves

### CODE REVIEW

**Comment by yadyn** [comment]
Thanks! I'll take a closer look at this probably sometime Monday.

Yes, generally this is the first thing to get updated, followed by the NuGet package, and then sometime after the CodeProject article whenever I stop being lazy.

I think I'm going to use this again in a new project I'm working on. There is a good chance it will motivate me to do some serious improvements soon!

**Comment by ygoe** [comment]
On 24.02.2013 07:51 CE(S)T, Sean A. Hanley wrote:

> Thanks! I'll take a closer look at this probably sometime Monday.

Cool. Should I also just send you pull requests for the other two things
I've done afterwards (which I've previously asked on CodeProject)?

> Yes, generally this is the first thing to get updated, followed by the
> NuGet package, and then sometime after the CodeProject article whenever
> I stop being lazy.

Okay, but I've only found about the GitHub repo because you mentioned it
in an answer on CodeProject. Maybe a general note could be useful that
there's often a newer version on GitHub which is what people should use
to start working on.

## 

Yves Goergen
Softwareentwicklung und Fotografie - http://unclassified.de
Diese Nachricht ist standardkonform mit OpenPGP digital signiert.

**Comment by yadyn** [comment]
Some of these I'm going to reject for now, but it's not because they aren't good. It's because with version 2.0 they will be solved already. Localization is a good example. I think I'm going to accept bug fixes only for 1.x and will be focusing improvements to the 2.x line as I expect there to be a lot of breaking API changes (mostly name changes though).

That said, don't be surprised to see some of this make it to 2.0. I like the named parameters overload of Show. I'd been planning on getting rid of the config struct for awhile now...

**Comment by yadyn** [comment]
I've merged the first three changes into the 2.0 code and I'll be crediting you.

Instead of throwing an exception, the code will now simply ignore any custom buttons defined if you also define command links.

Localization to come in 2.0 as well, but I've not gotten to implementing anything yet...

**Pull request closed without merging**
